version: 2

project_name: tgfs

builds:
  - main: ./cmd/fsb
    binary: tgfs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - ids:
      - tgfs
    images:
      - ghcr.io/shubham282raj/tgfs
    tags:
      - latest
      - "{{ .Tag }}"
    dockerfile: goreleaser.Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
